project:
  type: website
  resources:
    - app/

website:
  title: "Diversifix - Einfach diversitätssensibel."
  description: "DIVERSIFIX unterstützt den Einsatz diversitätssensibler Sprache und sensibilisiert für das Thema Diversität."
  favicon: img/favicon.ico
  image: img/diversifix-social-preview.png
  open-graph: true
  twitter-card: true
  site-url: https://diversifix.org
  repo-url: https://github.com/diversifix/diversifix-website
  search: false
  navbar:
    background: white
    logo: img/logo.png
    logo-alt: Diversifix
    title: false
    pinned: false
    collapse-below: lg
    right:
      - href: about.md
        text: Diversifix e. V. <br> Über den Verein
      - href: datenbank.md
        text: Datenbank <br> Zum Mitmachen
      - href: https://github.com/diversifix/diversifix
        text: Code <br> Auf Github
  page-footer:
    background: rgb(232, 232, 232)
    center:
      - href: impressum.md
        text: Impressum, Datenschutz & Lizenzen

format:
  html:
    lang: de
    max-width: 1024px
    backgroundcolor: rgb(232, 232, 232)
    linkcolor: rgb(27, 156, 216)
    css: styles.css
