project:
  type: website

website:
  title: "Diversifix"
  author: "Diversifix e. V."
  open-graph: true
  twitter-card: true
  site-url: https://diversifix.org
  repo-url: https://github.com/diversifix/diversifix-website
  search: false
  navbar:
    background: white
    logo: img/logo.png
    logo-alt: Diversifix
    title: false
    pinned: true
    collapse-below: md
    right:
      - href: datenbank.md
        text: Datenbank <br> Zum Mitmachen
      - href: about.md
        text: Diversifix e. V. <br> Über den Verein
      - icon: github
        href: https://github.com/diversifix
        aria-label: Code auf Github
  page-footer:
    background: rgb(232, 232, 232)
    center:
      - href: impressum.md
        text: Impressum, Datenschutz & Lizenzen

format:
  html:
    lang: de
    theme: cosmo
    max-width: 1024px
    backgroundcolor: rgb(232, 232, 232)
    linkcolor: rgb(27, 156, 216)
    css: styles.css
